#!/usr/bin/env bash
# This script displays a list of currently running processes
# It must show all processes, for all users, including those which might not have a TTY
# Displays a user-oriented format
# Shows process hierarchy

ps -a -x -u -f
