#!/usr/bin/env bash
# This script writes "I am alive" to the file /tmp/my_process and pauses for 2 seconds between every "I am alive"
while true
do
    sudo bash -c "echo \"I am alive!\" >> /tmp/my_process"
    sleep 2
done
