#!/usr/bin/env bash
# a script to change user to nginx to run nginx webserver 
pkill apache2 
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf 
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default 
sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default 
service nginx start
